config/routes.rb
Rails.application.routes.draw do
  resources :hours
  resources :caregivers
  resources :clients
  devise_for :users
	root 'clients#index'

end

app/models/caregiver.rb
class Caregiver < ActiveRecord::Base
	has_many :hours
	has_many :clients, through: :hours

	validates :name, presence: true
	validates :phone, presence: true
	
	def client_list
		list = Array.new
		self.clients.all.each do |c|
			if !list.include?( [c.name, c.id] )
				list << [c.name, c.id]
			end
		end
		return list
	end
	
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :hours
	has_many :caregivers, through: :hours

	validates :name, presence: true
	validates :phone, presence: true

	def caregiver_list
		list = Array.new
		self.caregivers.all.each do |c|
			if !list.include?( [c.name, c.id] )
				list << [c.name, c.id]
			end
		end
		return list
	end

end

app/models/hour.rb
class Hour < ActiveRecord::Base
	belongs_to :client
	belongs_to :caregiver

	validates :client_id, 
		presence: true, 
		numericality: { only_integer: true }
	validates :caregiver_id, 
		presence: true, 
		numericality: { only_integer: true }
	validates :time, 
		presence: true, 
		numericality: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_action :set_caregiver, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /caregivers
  # GET /caregivers.json
  def index
    @caregivers = Caregiver.all.order(name: :asc)
  end

  # GET /caregivers/1
  # GET /caregivers/1.json
  def show
  	@client_list = @caregiver.client_list
  	@hours_total = @caregiver.hours.all
  end

  # GET /caregivers/new
  def new
    @caregiver = Caregiver.new
  end

  # GET /caregivers/1/edit
  def edit
  end

  # POST /caregivers
  # POST /caregivers.json
  def create
    @caregiver = Caregiver.new(caregiver_params)

    respond_to do |format|
      if @caregiver.save
        format.html { redirect_to @caregiver, notice: 'Caregiver was successfully created.' }
        format.json { render :show, status: :created, location: @caregiver }
      else
        format.html { render :new }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caregivers/1
  # PATCH/PUT /caregivers/1.json
  def update
    respond_to do |format|
      if @caregiver.update(caregiver_params)
        format.html { redirect_to @caregiver, notice: 'Caregiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @caregiver }
      else
        format.html { render :edit }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caregivers/1
  # DELETE /caregivers/1.json
  def destroy
    @caregiver.destroy
    respond_to do |format|
      format.html { redirect_to caregivers_url, notice: 'Caregiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caregiver
      @caregiver = Caregiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caregiver_params
      params.require(:caregiver).permit(:name, :phone, :birthday)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  require "./lib/tasks/date_based_model_functions.rb"

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order(name: :asc)
  	@upcoming_birthdays_clients = upcoming_birthdays_clients
  	@upcoming_birthdays_caregivers = upcoming_birthdays_caregivers
  	@upcoming_client_agreements = upcomming_client_agreement_renewals
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  	@caregiver_list = @client.caregiver_list
  	@caregiver_time_table = @client.hours.all
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, 
      	:address, 
      	:phone, 
      	:hours, 
      	:emergency_contact, 
      	:emergency_contact_phone, 
      	:active, 
      	:birthdate, 
      	:services_started, 
      	:services_ended,
      	:client_agreement)
    end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :set_hour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all.order(created_at: :desc)
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
  end

  # GET /hours/new
  def new
  	@clients = Client.all
  	@caregivers = Caregiver.all
    @hour = Hour.new
  end

  # GET /hours/1/edit
  def edit
  	@clients = Client.all
  	@caregivers = Caregiver.all
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(hour_params)

    respond_to do |format|
      if @hour.save
        format.html { redirect_to @hour, notice: 'Hour was successfully created.' }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to @hour, notice: 'Hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url, notice: 'Hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hour
      @hour = Hour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hour_params
      params.require(:hour).permit(:client_id, :caregiver_id, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def header_html(text)
		return '<div class="col-sm-12" id="featured">   
  		<div class="page-header text-muted">
  			<h2>' + text + '</h2>
  		</div> 
		</div>'
	end
	
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/caregivers/edit.html.erb
<%=raw header_html('Edit Caregiver') %>

<%= render 'form' %>

<%= link_to 'Show', @caregiver %> |
<%= link_to 'Back', caregivers_path %>

app/views/caregivers/index.html.erb
<p id="notice"><%= notice %></p>
<%=raw header_html('Caregiver List') %>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caregivers.each do |caregiver| %>
      <tr>
        <td><%= caregiver.name %></td>
        <td><%= caregiver.phone %></td>
        <td><%= caregiver.birthday %></td>
        <td><%= link_to 'Show', caregiver %></td>
        <td><%= link_to 'Edit', edit_caregiver_path(caregiver) %></td>
        <td><%= link_to 'Destroy', caregiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caregiver', new_caregiver_path %>

app/views/caregivers/show.html.erb
<p id="notice"><%= notice %></p>

<%=raw header_html('Caregiver Info') %>
<div class='row'>
	<div class='col-sm-7'>
		<p>
		  <strong>Name:</strong>
		  <%= @caregiver.name %>
		</p>
		<p>
		  <strong>Phone:</strong>
		  <%= @caregiver.phone %>
		</p>
		<p>
		  <strong>Birthday:</strong>
		  <%= @caregiver.birthday %>
		</p>

		<p>
		  <strong>Total Hours:</strong>
		  <%= @hours_total.sum(:time) %>
		</p>
		<%= link_to 'Edit', edit_caregiver_path(@caregiver) %> | <%= link_to 'Back', caregivers_path %>
	</div>
	<div class='col-sm-5'>
		<table class='table'>
			<thead>
				<th>Clients</th>
			</thead>
			<tbody>
				<% @caregiver.client_list.each do |c| %>
					<tr> <td> <%= link_to c[0], client_path( c[1] ) %> </td> </tr>
				<% end %>
			</tbody>
		</table>	
		<table class='table'>
			<thead>
				<tr>
					<th>TimeFrame</th>
					<th>Hours</th>
					<th>Client</th>
				<tr>
			</thead>
			<tbody>
				<% @hours_total.each do |h| %>
					<tr> 
						<td> <%= link_to h.created_at.to_date, hour_path( h.id ) %> </td> 
						<td> <%= h.time %> </td>
						<td> <%= h.client.name %> </td>
				</tr>
				<% end %>
			</tbody>
		</table>			
	</div>
</div>
<div class="chart">
	<%= column_chart [ # Data Input ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		{ name: "Weekly Hours", data: @hours_total.group_by_week( :created_at, format: "%m/%d/%y" ).sum('time') },
		{ name: "Visits", data: @hours_total.group_by_week( :created_at, format: "%m/%d/%y" ).count }
	],
	{ library: # Style Input ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
		{ height: 'null', # null or number in pixels
			width: 'null', # null or number in pixels
			title: "#{@caregiver.name}'s Care Timeline", # ===================================
			# titlePostion: "center", # Does not do anything
			titleTextStyle: {
				fontName: 'Helvetica',
				fontSize: 22,
				bold: true,
				italic: true,
      	color: "black",
      	auraColor: 'none',
      	opacity: 1.0
			} , # ---------------------------------------------------------------
			hAxis: { # ==========================================================
				title: "Week", # ///////////////////////////////////////////////////
				viewWindow: {
					min: 'null', # null or number
					max: 'null', # null or number
					},
				titleTextStyle: {
					fontName: 'Helvetica',
					fontSize: 22,
					bold: true,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
				}, 
				textStyle: { # This styles the x-axis break point labels //////////
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
        },
      	gridlines: { # ////////////////////////////////////////////////////
        	color: "transparent"  # options -> transparent, line
      	}, 
      	baselineColor: "#ccc",
      }, # ----------------------------------------------------------------
			vAxis: { # ==========================================================
				title: "Hours of Care", # ////////////////////////////////////
				titleTextStyle: {
					fontName: 'Helvetica',
					fontSize: 22,
					bold: true,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
				}, 
				textStyle: { # This styles the y-axis break point labels //////////
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
      	},
      	gridlines: { # ////////////////////////////////////////////////////
        	color: "transparent"  # options -> transparent, color
      	}, 
      	baselineColor: "#ccc",
      	direction: 1, # 1, -1
      	format: 'short', # none, decimal, scientific, currency, percent, short, long
      	viewWindow: {} 
    	}, # ---------------------------------------------------------------
   		tooltip: { # ========================================================
   			# this is the pop-up of data point information
   			ignoreBounds: false,
   			isHtml: false,
   			showColorCode: true,
   			textStyle: {
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0	
      	},
      	trigger: 'focus' # focus, none, selection
   		}, # ---------------------------------------------------------------
   		trendlines: {
   			# 0 => {
   			# 	color: "black",
   			# 	degree: 3,å
   			# 	labelInLegend: "Trendline",
   			# 	lineWidth: 2,
   			# 	opacity: 1.0,
   			# 	pointSize: 1,
   			# 	pointsVisible: false,
   			# 	showR2: true,
   			# 	type: 'linear', #linear, exponential, polynomial
   			# 	visibleInLegend: true
   			# }
   		},
    	backgroundColor: { # ===============================================
    		stroke: '#666',
    		strokeWidth: 0,
    		fill: 'white'
    	}, # ---------------------------------------------------------------
    	legend: { #=========================================================
    		position: 'bottom', # bottom, left, in, none, right, top
    		alignment: 'center', # start, center, end
    		textStyle: {

    		}
    	}, # ---------------------------------------------------------------
			animation: { # ======================================================
				duration: 1000, # in milliseconds
				easing: 'inAndOut', # Animation speed: linear, in, out, inAndOut
				startup: true
			}, # ----------------------------------------------------------------
			chartArea: { # ======================================================
				# gives options but should leave to automatic
				# left: 100, top: 10, height: '85%', width: '50%' 
			}, # ----------------------------------------------------------------
    	theme: 'null', # null, maximized
			# pie charts
			is3D: true, 
			# line graphs and scatter plots
			pointSize: 6,  
			curveType: "line" # 2 options -> function, line
   #  	annotations: { # ===================================================
   #  		# annotations are reference items placed on your chart
   #  		# not sure if this is functional in chartkick
   #  		alwaysOutside: true,
   #  		highContrast: true,
   #  		textStyle: {
   #  			fontName: 'Helvetica',
	 #        fontSize: 14,
	 #        bold: false,
	 #        italic: false,
   #     	  color: "black",
   #     	  auraColor: 'none',
   #     	  opacity: 1.0
   #  		},
   #  		boxStyle: {
   #  			stroke: '#888',
   #  			strokeWidth: 1,
   #  			rx: 10,
   #  			ry: 10,
   #  			gradient: {
   #  				color1: '#fbf6a7',
   #  				color2: '#33b679',
   #  				x1: '0%', y1: '0%',
   #  				x2: '100%', y2: '100%',
   #  				useObjectBoundingBoxUnits: true
   #  			}
   #  		}
   #  	}, # --------------------------------------------------------------					
		} 
	} %>
</div>

app/views/clients/index.html.erb
<%=raw header_html('Listing Clients') %>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Hours</th>
      <th>Emergency contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.address %></td>
        <td><%= client.phone %></td>
        <td><%= client.hours.all.sum(:time) %></td>
        <td><%= client.emergency_contact %> | <%= client.emergency_contact_phone %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="col-sm-12" id="featured">   
  <div class="page-header text-muted">
  	<h3>Upcoming Client Agreement Renewals:</h3>
  </div> 
</div>
<table class='table'>
	<tbody>
		<% @upcoming_client_agreements.each do |bd| %>
			<tr>
				<td><%= link_to bd[0], client_path( bd[1] ) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<div class="col-sm-12" id="featured">   
  <div class="page-header text-muted">
  	<h3>Upcoming Client Birthdays:</h3>
  </div> 
</div>
<table class='table'>
	<tbody>
		<% @upcoming_birthdays_clients.each do |bd| %>
			<tr>
				<td><%= link_to bd[1], client_path( bd[2] ) %></td>
				<td><%= bd[0] %></td>  
			</tr>
		<% end %>
	</tbody>
</table>

<div class="col-sm-12" id="featured">   
  <div class="page-header text-muted">
  	<h3>Upcoming Caregiver Birthdays:</h3>
  </div> 
</div>
<table class='table'>
	<tbody>
		<% @upcoming_birthdays_caregivers.each do |bd| %>
			<tr>
				<td><%= link_to bd[1], caregiver_path( bd[2] ) %></td>
				<td><%= bd[0] %></td>  
			</tr>
		<% end %>
	</tbody>
</table>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%=raw header_html('Client Info') %>

<div class='row'>
	<div class='col-sm-7'>
		<p>
		  <strong>Name:</strong>
		  <%= @client.name %>
		</p>
		<p>
		  <strong>Address:</strong>
		  <%= @client.address %>
		</p>
		<p>
		  <strong>Phone:</strong>
		  <%= @client.phone %>
		</p>
		<p>
		  <strong>Total Hours:</strong>
		  <%= @client.hours.all.sum(:time) %>
		</p>
		<p>
		  <strong>Emergency contact:</strong>
		  <%= @client.emergency_contact %>
		</p>
		<p>
		  <strong>Emergency contact phone:</strong>
		  <%= @client.emergency_contact_phone %>
		</p>
		<p>
		  <strong>Active:</strong>
		  <%= @client.active %>
		</p>
		<p>
		  <strong>Birthdate:</strong>
		  <%= @client.birthdate.to_formatted_s(:long) %>
		</p>
		<p>
		  <strong>Services started:</strong>
		  <%= @client.services_started.to_formatted_s(:long) %>
		</p>
		<p>
		  <strong>Services ended:</strong>
		  <%= @client.services_ended %>
		</p>
		<p>
		  <strong>Client Agreement Renewal Date:</strong>
		  <%= @client.client_agreement %>
		</p>
		<p>
			<strong>Total hours:</strong>
			<%= @client.hours.all.sum(:time) %>
		</p>
		<%= link_to 'Edit', edit_client_path(@client) %> | <%= link_to 'Back', clients_path %>
	</div>

	<div class='col-sm-5'>
		<table class='table'>
			<thead>
				<th>Caregivers</th>
			</thead>
			<tbody>
				<% @client.caregiver_list.each do |c| %>
					<tr> <td> <%= link_to c[0], caregiver_path(id: c[1]) %> </td>  </tr>
				<% end %>
			</tbody>
		</table>		
		<table class='table'>
			<thead>
				<th>Caregivers Order</th>
			</thead>
			<tbody>
				<% @caregiver_time_table.each do |h| %>
					<tr><td> <%= link_to h.created_at.to_date, hour_path(h.id) %> </td><td><%= h.caregiver.name %> </td><td> <%= h.time %> hr</td></tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="chart">
	<%= column_chart [ # Data Input ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		{ name: "Weekly Hours", data: @caregiver_time_table.group_by_week( :created_at, format: "%m/%d/%y" ).sum('time') },
		{ name: "Visits", data: @caregiver_time_table.group_by_week( :created_at, format: "%m/%d/%y" ).count }
	],
	{ library: # Style Input ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
		{ height: 'null', # null or number in pixels
			width: 'null', # null or number in pixels
			title: "#{@client.name}'s Care Timeline", # ===================================
			# titlePostion: "center", # Does not do anything
			titleTextStyle: {
				fontName: 'Helvetica',
				fontSize: 22,
				bold: true,
				italic: true,
      	color: "black",
      	auraColor: 'none',
      	opacity: 1.0
			} , # ---------------------------------------------------------------
			hAxis: { # ==========================================================
				title: "Week", # ///////////////////////////////////////////////////
				viewWindow: {
					min: 'null', # null or number
					max: 'null', # null or number
					},
				titleTextStyle: {
					fontName: 'Helvetica',
					fontSize: 22,
					bold: true,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
				}, 
				textStyle: { # This styles the x-axis break point labels //////////
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
        },
      	gridlines: { # ////////////////////////////////////////////////////
        	color: "transparent"  # options -> transparent, line
      	}, 
      	baselineColor: "#ccc",
      }, # ----------------------------------------------------------------
			vAxis: { # ==========================================================
				title: "Hours of Care", # ////////////////////////////////////
				titleTextStyle: {
					fontName: 'Helvetica',
					fontSize: 22,
					bold: true,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
				}, 
				textStyle: { # This styles the y-axis break point labels //////////
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0
      	},
      	gridlines: { # ////////////////////////////////////////////////////
        	color: "transparent"  # options -> transparent, color
      	}, 
      	baselineColor: "#ccc",
      	direction: 1, # 1, -1
      	format: 'short', # none, decimal, scientific, currency, percent, short, long
      	viewWindow: {} 
    	}, # ---------------------------------------------------------------
   		tooltip: { # ========================================================
   			# this is the pop-up of data point information
   			ignoreBounds: false,
   			isHtml: false,
   			showColorCode: true,
   			textStyle: {
					fontName: 'Helvetica',
					fontSize: 14,
					bold: false,
					italic: false,
        	color: "black",
        	auraColor: 'none',
        	opacity: 1.0	
      	},
      	trigger: 'focus' # focus, none, selection
   		}, # ---------------------------------------------------------------
   		trendlines: {
   			# 0 => {
   			# 	color: "black",
   			# 	degree: 3,å
   			# 	labelInLegend: "Trendline",
   			# 	lineWidth: 2,
   			# 	opacity: 1.0,
   			# 	pointSize: 1,
   			# 	pointsVisible: false,
   			# 	showR2: true,
   			# 	type: 'linear', #linear, exponential, polynomial
   			# 	visibleInLegend: true
   			# }
   		},
    	backgroundColor: { # ===============================================
    		stroke: '#666',
    		strokeWidth: 0,
    		fill: 'white'
    	}, # ---------------------------------------------------------------
    	legend: { #=========================================================
    		position: 'bottom', # bottom, left, in, none, right, top
    		alignment: 'center', # start, center, end
    		textStyle: {

    		}
    	}, # ---------------------------------------------------------------
			animation: { # ======================================================
				duration: 1000, # in milliseconds
				easing: 'inAndOut', # Animation speed: linear, in, out, inAndOut
				startup: true
			}, # ----------------------------------------------------------------
			chartArea: { # ======================================================
				# gives options but should leave to automatic
				# left: 100, top: 10, height: '85%', width: '50%' 
			}, # ----------------------------------------------------------------
    	theme: 'null', # null, maximized
			# pie charts
			is3D: true, 
			# line graphs and scatter plots
			pointSize: 6,  
			curveType: "line" # 2 options -> function, line
   #  	annotations: { # ===================================================
   #  		# annotations are reference items placed on your chart
   #  		# not sure if this is functional in chartkick
   #  		alwaysOutside: true,
   #  		highContrast: true,
   #  		textStyle: {
   #  			fontName: 'Helvetica',
	 #        fontSize: 14,
	 #        bold: false,
	 #        italic: false,
   #     	  color: "black",
   #     	  auraColor: 'none',
   #     	  opacity: 1.0
   #  		},
   #  		boxStyle: {
   #  			stroke: '#888',
   #  			strokeWidth: 1,
   #  			rx: 10,
   #  			ry: 10,
   #  			gradient: {
   #  				color1: '#fbf6a7',
   #  				color2: '#33b679',
   #  				x1: '0%', y1: '0%',
   #  				x2: '100%', y2: '100%',
   #  				useObjectBoundingBoxUnits: true
   #  			}
   #  		}
   #  	}, # --------------------------------------------------------------					
		} 
	} %>
</div>

app/views/layouts/_sidebar.html.erb
<!-- sidebar -->
<div class="column col-sm-3" id="sidebar">
  <%= link_to "HamdardCenter", root_path, class: 'logo' %>
  <ul class="nav nav-pills nav-stacked nav-tabs">
    <li><%= link_to 'Client List', root_path, {role: "presentation", class: "active"} %></li>
    <li><%= link_to 'Caregiver List', caregivers_path %></li>
    <li><%= link_to 'Appointments List', hours_path %></li>
    <li><%= link_to 'Add New Client', new_client_path %></li>
    <li><%= link_to 'Add New Caregiver', new_caregiver_path %></li>
    <li><%= link_to 'Add New Appointment', new_hour_path %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  </ul>
  <ul class="nav hidden-xs" id="sidebar-footer">
    <li>
      <a href="http://www.bootply.com"><h3>Basis</h3>Made with <i class="glyphicon glyphicon-heart-empty"></i> by Bootply</a>
    </li>
  </ul>
</div>
<!-- /sidebar -->